# Generated by Django 4.0.3 on 2022-03-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='status',
            new_name='_status',
        ),
    ]
