# Generated by Django 4.0.3 on 2022-03-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(default='not activated', max_length=50),
        ),
    ]
